### ISSUE TITLE
Discussion on #/activereportsjs/docs/ReportAuthorGuide/QuickStart/get-started-with-/Get-Started-With-Mail-Merge-Reports

### ISSUE THREAD

**Issue by Tomdanizer** [GrapeCity/activereportsjs-demos#10]
Type Your Comment Here

Promotion is misspelled as `Promution` in the line `By default, each Promution record includes 14 fields, but we don't need them all. `
---
#### /activereportsjs/docs/ReportAuthorGuide/QuickStart/get-started-with-/Get-Started-With-Mail-Merge-Reports

**Comment by sAbakumoff** [comment]
Thanks for reporting this misprint. We fixed it.
