### ISSUE TITLE
Discussion on #/activereportsjs/docs/v1/GettingStarted/React-Component

### ISSUE THREAD

**Issue by MrArun005** [GrapeCity/activereportsjs-demos#14]
Type Your Comment Here

i am unable to use css file of designer. The import statement is giving me errors
Operation on an invalid type
      in C:\Users\malliar\node_modules\@grapecity\activereports\styles\ar-js-designer.css (line 1, column 217501)
 @ C:/Users/malliar/node_modules/@grapecity/activereports/styles/ar-js-designer.css 2:14-230 21:1-42:3 22:19-235
---
#### /activereportsjs/docs/v1/GettingStarted/React-Component

**Comment by sAbakumoff** [comment]
Hello,
Please use the most recent version of the walkthrough:
https://www.grapecity.com/activereportsjs/docs/GettingStarted/QuickStart-ARJS-Designer-Component/QuickStart-React
