### ISSUE TITLE
Discussion on #features/viewer-exportsettings

### ISSUE THREAD

**Issue by MrArun005** [GrapeCity/activereportsjs-demos#15]
Type Your Comment Here

---
#### features/viewer-exportsettings
i am able to see export options in the viewer and suddenly it is vanishing. The parameters part itself is not coming up.
May i know what might be the issue out here

**Comment by sAbakumoff** [comment]
Hello,
I just checked the demo on https://www.grapecity.com/activereportsjs/demos/features/viewer-exportsettings/purejs and it works fine on my side.
If you experience the issue with your application, please send the request via the support channel - https://www.grapecity.com/my-account/my-support/newcase
