### ISSUE TITLE
Discussion on #Reports/RuntimeFilters

### ISSUE THREAD

**Issue by aliraza9996** [GrapeCity/activereportsjs-demos#16]
Type Your Comment Here
This page does not tell how to define custom codes?
I can not find anywhere in design? Can you please highlight?

---
#### Reports/RuntimeFilters

**Comment by aliraza9996** [comment]
I see it here https://www.grapecity.com/activereportsjs/docs/DeveloperGuide/advanced/custom-code

But we are kind of using our backend to send all the data, and reports are generated on the FE.
It seems to be a really ambiguous functionality in terms of making code generic. I have 100s of reports and I can not register for functions on the FE for every report individually.
Active report js should have an inbuild functionality to define codes inside the ARJS designer.

**Comment by sAbakumoff** [comment]
Hello,
Please send your questions regarding the product functionality via the support channel at https://www.grapecity.com/support
