### ISSUE TITLE
Discussion on #features/viewer-runtime-data-binding

### ISSUE THREAD

**Issue by vmullapudifrontline** [GrapeCity/activereportsjs-demos#19]
Type Your Comment Here

Hello Team,
we are using latest version of ActiveReportsJS in our react application. Below are dependencies

```
"@grapecity/activereports": "^4.2.1",
"@grapecity/activereports-localization": "^3.2.2",
"@grapecity/activereports-react": "^3.2.0",
```

used code:

```
const data = await loadData();
  const report = await loadReport();
  report.DataSources[0].ConnectionProperties.ConnectString =
    "jsondata=" + JSON.stringify(data);
  viewerRef.current.Viewer.open(report);
```

here is the error on viewerRef.current.Viewer.open(report);
details:undefined
message:"Cannot read properties of undefined (reading 'trim')"
severity: "error"

Note: Export is working well with the same report
---
#### features/viewer-runtime-data-binding

**Comment by sAbakumoff** [comment]
Hello,
Please post the support ticket via the form at https://developer.mescius.com/my-account/my-support
