### ISSUE TITLE
Request for Assistance: Custom Styling in ActiveReportsJS (React v4.2.2)

### ISSUE THREAD

**Issue by sajeeljintech** [GrapeCity/activereportsjs-demos#21]
Hi Support Team,

I've been using ActiveReportsJS for our system, and I recently encountered a requirement to implement additional styling options within the style dropdown in ActiveReportsJS designer view.
<img width="394" alt="Screenshot 2024-03-25 at 4 46 59 PM" src="https://github.com/GrapeCity/activereportsjs-demos/assets/9428134/faba9283-7308-4692-ba40-805db14d9f3c">

Upon consulting the documentation, I discovered that the available styling properties are fixed, comprising a combination of background color, foreground color, major and minor font variations, etc. Unfortunately, it seems that I cannot add new options or update existing ones directly.

According to the documentation, the only workaround seems to be creating a custom theme that overrides the values of these options. However, this approach still restricts me to only two font variations/sizes: Major and Minor.

Links for reference:
Documentation on Themes: [ActiveReportsJS Themes](https://developer.mescius.com/activereportsjs/docs/ReportAuthorGuide/Themes#style-property)
API Reference: [ActiveReportsJS API - ThemeInfo](https://developer.mescius.com/activereportsjs/api/modules/ReportDesigner#themeinfo)

Moreover, attempting this customization with the ActiveReportsJS React package ([@grapecity/activereports-react](https://www.npmjs.com/package/@grapecity/activereports-react)) has led to some complications. It registers the custom theme but fails to apply it.

<img width="651" alt="Themes" src="https://github.com/GrapeCity/activereportsjs-demos/assets/9428134/60255e9c-cdfb-4202-8793-96e0d2615002">

I'm seeking guidance on how I might expand the available font variations beyond the current limitation of two, as well as how to integrate additional custom style properties into the style dropdown.

Could you please advise if there's a solution to achieve these requirements that I might have overlooked?

Thank you for your assistance.

Best regards,
Sajeel

**Comment by sAbakumoff** [comment]
Hello,
Please send your question via the support channel at https://developer.mescius.com/my-account/my-support
