### ISSUE TITLE
Discussion on #/activereportsjs/docs/DeveloperGuide/ActiveReportsJSViewer/Customization

### ISSUE THREAD

**Issue by Tomdanizer** [GrapeCity/activereportsjs-demos#4]
Type Your Comment Here
The internal id $continuouspagemode is incorrect as it does not work. The correct value appears to be $continuousmode

---
#### /activereportsjs/docs/DeveloperGuide/ActiveReportsJSViewer/Customization

**Comment by sAbakumoff** [comment]
Thanks for bringing this issue to our attention! I have fixed the mistake in the document.
