### ISSUE TITLE
Discussion on #/activereportsjs/docs/DeveloperGuide/ActiveReportsJSDesignerComponent/Action-Handlers

### ISSUE THREAD

**Issue by lucjanl** [GrapeCity/activereportsjs-demos#5]
Type Your Comment Here

The link in "Check [User Interface topic](https://www.grapecity.com/activereportsjs/docs/ReportAuthorGuide/Report-Designer-Interface)" is invalid (404)
---
#### /activereportsjs/docs/DeveloperGuide/ActiveReportsJSDesignerComponent/Action-Handlers

**Comment by sAbakumoff** [comment]
Hello,
Thanks for bringing this issue to our attention. I looked at the document and https://www.grapecity.com/activereportsjs/docs/DeveloperGuide/ActiveReportsJSDesignerComponent/Action-Handlers and the "User Interface topc" link works fine for me. Am I missing something?

**Comment by lucjanl** [comment]
No, now it works well. This morning it returned 404
