### ISSUE TITLE
Discussion on #/activereportsjs/api/modules/Interops.Angular

### ISSUE THREAD

**Issue by lucjanl** [GrapeCity/activereportsjs-demos#6]
Type Your Comment Here

The link in "To use it, please, refer to [documentation](https://www.grapecity.com/docs/GettingStarted/Angular-Component)." is invalid (404)

![image](https://user-images.githubusercontent.com/8089722/165277351-adb4b118-54b2-4cee-89a5-6dd825c16f2a.png)

---
#### /activereportsjs/api/modules/Interops.Angular

**Comment by sAbakumoff** [comment]
Thanks for bringing this issue to our attention, we will fix it!
The correct link is https://www.grapecity.com/activereportsjs/docs/GettingStarted/QuickStart/QuickStart-Angular.

**Comment by sAbakumoff** [comment]
The issue has been fixed
