### ISSUE TITLE
Discussion on #/activereportsjs/api/v3.2/interfaces/ReportViewer.ReportSettings

### ISSUE THREAD

**Issue by asandeveloper1** [GrapeCity/activereportsjs-demos#9]
Type Your Comment Here

There is no sample to enable developers to know how to use this Settings 

---
#### /activereportsjs/api/v3.2/interfaces/ReportViewer.ReportSettings

**Comment by sAbakumoff** [comment]
Hello,
You can find the sample of using the Resource Locator on https://www.grapecity.com/activereportsjs/demos/features/viewer-resource-locator/purejs
The sample of ReportParams is on https://www.grapecity.com/activereportsjs/demos/features/viewer-set-parameter-values/purejs
